Repository trailofbits/vast, pull requests merged in 2023-03, with the labels that each got.

#237 Add missing libraries to linking targets
  tools/vast-front/CMakeLists.txt
  tools/vast-opt/CMakeLists.txt
Labels: bug, infrastructure

#239 git: Bump up actions time limit.
  .github/workflows/build.yml
Labels: infrastructure

#261 cg: Add missing label scope to codegen driver.
  include/vast/Translation/CodeGen.hpp
Labels: bug
