Repository trailofbits/vast, pull requests merged in 2023-10, with the labels that each got.

#412 README: Update to reflect llvm-17 update.
  README.md
Labels: documentation, enhancement

#414 Generalize emit mlir options and remove duplicits.
  include/vast/Frontend/FrontendAction.hpp
  include/vast/Frontend/GenAction.hpp
  lib/vast/Frontend/GenAction.cpp
  test/vast/Dialect/HighLevel/glob-front-a.c
  test/vast/Dialect/HighLevel/glob-front-b.c
  test/vast/Dialect/HighLevel/glob-front-c.c
  test/vast/Dialect/HighLevel/hello-world.c
  tools/vast-front/compiler_invocation.cpp
Labels: enhancement, frontend

#415 Add issue templates.
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement, infrastructure

#426 Fix compilation with clang 15
  include/vast/CodeGen/CodeGenTypeVisitor.hpp
Labels: bug, build
