Repository trailofbits/vast, pull requests merged in 2024-02, with the labels that each got.

#494 Fix memory corruption related to unregistered linkage attribute.
  include/vast/Dialect/Core/Core.td
  include/vast/Dialect/Core/CoreAttributes.td
  include/vast/Dialect/Core/Linkage.td
  include/vast/Dialect/LowLevel/LowLevelOps.hpp
Labels: bug, mlir

#508 Update checkout actions to v4
  .github/workflows/build.yml
  .github/workflows/devcontainer.yml
  .github/workflows/linter.yml
  .github/workflows/prerelease.yml
Labels: enhancement

#509 Fix variables in llvm test suite workflow
  .github/workflows/llvm-ts-run.yml
Labels: bug

#510 Add related projects to VAST website.
  docs/Projects/related.md
  www/mkdocs.yml
Labels: enhancement, www

#511 gh: Fix result name for binary test run.
  .github/workflows/llvm-ts-run.yml
Labels: bug
