Repository trailofbits/vast, pull requests merged in 2024-04, with the labels that each got.

#546 Bump runner cmake version to 3.29.2.
  .devcontainer/Dockerfile
Labels: infrastructure

#547 Update devcontainer cpack and ctest paths.
  .devcontainer/reinstall-cmake.sh
Labels: infrastructure

#548 Fix pages build path
  .github/workflows/prerelease.yml
Labels: bug

#551 gh: Fix doc build dependency.
  .github/workflows/prerelease.yml
Labels: bug, infrastructure

#552 gh: Bump sv-comp test suite time limit.
  .github/workflows/prerelease.yml
Labels: bug, infrastructure

#555 gh: Fix repostiory path in sv-comp evaluator.
  .github/workflows/prerelease.yml
Labels: bug

#557 gh: Configure VAST before building docs.
  .github/workflows/prerelease.yml
Labels: bug

#578 test: Use cc instead of hard-coded clang-X binary.
  test/lit.cfg.py
  test/vast/Compile/ObjectFiles/float-a.c
  test/vast/Compile/ObjectFiles/identity-a.c
  test/vast/Compile/ObjectFiles/struct-a.c
  test/vast/Compile/ObjectFiles/struct-b.c
  test/vast/Compile/ObjectFiles/void-return-a.c
Labels: bug, infrastructure
