Repository trailofbits/vast, pull requests merged in 2024-01, with the labels that each got.

#473 Update deprecated pre-release action.
  .github/workflows/prerelease.yml
Labels: enhancement, infrastructure

#474 Fir prerelease vast package path.
  .github/workflows/prerelease.yml
Labels: bug, infrastructure

#475 Fix prerelease package regex.
  .github/workflows/prerelease.yml
Labels: bug

#479 Simplify package naming.
  CMakeLists.txt
Labels: enhancement

#487 util: Clean up and fix UB in `VAST_[CHECK,ASSERT,UNREACHABLE]` macros.
  include/vast/Util/Warnings.hpp
Labels: bug
