Repository trailofbits/vast, pull requests merged in 2024-05, with the labels that each got.

#580 Bump LLVM version in docs/guide.
  docs/GettingStarted/build.md
Labels: bug, documentation

#586 Disable unsupported dialect
  include/vast/CodeGen/CodeGenOptions.hpp
  include/vast/Frontend/Options.hpp
  lib/vast/CodeGen/CodeGenDriver.cpp
Labels: frontend

#587 Refactor core attributes naming
  include/vast/Dialect/Core/CoreAttributes.hpp
  include/vast/Dialect/Core/CoreAttributes.td
Labels: core

#593 Add runs without unsupported dialect to CI
  .github/workflows/prerelease.yml
Labels: infrastructure

#598 gh: Fix suffix extraction from environment in actions arguments.
  .github/workflows/prerelease.yml
Labels: bug, infrastructure

#600 Fix how we get rid of unnecessary unsup runs in CI
  .github/workflows/prerelease.yml
Labels: bug, infrastructure

#603 Bump C++ standard to 23
  cmake/project_settings.cmake
Labels: build
